// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/palette/PaletteA.tsx": () => import("../components/mockups/palette/PaletteA.tsx"),
  "./components/mockups/palette/PaletteB.tsx": () => import("../components/mockups/palette/PaletteB.tsx"),
  "./components/mockups/palette/PaletteC.tsx": () => import("../components/mockups/palette/PaletteC.tsx")
};
